version: "3.7"

services:
  web:
    build:
      context: ./docker/web/
      dockerfile: Dockerfile
    volumes:
      - .:/app
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      STAGE: local
      DOMAINS:  'localhost -> http://web:80'